<div id="errors" style="padding: 0.2em 0.2em .2em 0.75em; width: 435px; display: none;"  class="ui-state-error ui-corner-all"> 
	<p>
		<span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span> 
		Please Correct The Following Errors:
	</p>
	<ul id="errorList"></ul>
</div>
<table cellspacing="0px" cellpadding="5px" class="baseline">
    <tbody>
        <tr>            
            <th style="text-align: left;">Edit Description</th>
       </tr>
            </tbody>
</table>


<div>
	<textarea id="edit_material_location" style="width:99.5%;min-height:100px;"><?= $this->material->material_location; ?></textarea>
</div><br/>
<!--div class="ui-dialog-buttonset">
	<button onclick="project.saveMaterialLocation(<?= $project_id ?>);" type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
		<span class="ui-button-text">Save</span>
	</button>&nbsp;
	<button type="button"  onclick="project.cancelMaterialLocation();" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
		<span class="ui-button-text">Cancel</span>
	</button>
</div--><br/><br/>