<table cellspacing="0px" cellpadding="5px" class="baseline">
    <tbody>
        <tr>            
            <th style="text-align: left;">Description</th>
       </tr>
       <tr>          
            <td>
                <div id="div-material-location">
                    <?= is_null($this->projectinfo->material_location) ? '&nbsp;' : nl2br($this->projectinfo->material_location) ?>
                </div>                
            </td>
        </tr>
        
    </tbody>
</table>    