<?

$ver = ProNav_Utils::APP_VERSION;
$this->headScript()->appendFile('/js/project.js?v='.$ver);
$this->headScript()->appendFile('/js/acquisition.js?v='.$ver);
$this->headScript()->appendFile('/js/accounting.js?v='.$ver);
$this->headScript()->appendFile('/js/project_team.js?v='.$ver);
$this->headScript()->appendFile('/js/note.js?v='.$ver);
$this->headScript()->appendFile('/js/project_tasks.js?v='.$ver);
$this->headScript()->appendFile('/js/submittals.js?v='.$ver);
$this->headScript()->appendFile('/js/rfis.js?v='.$ver);
$this->headScript()->appendFile('/js/project_analysis.js?v='.$ver);
$this->headScript()->appendFile('/js/project_labor.js?v='.$ver);
$this->headScript()->appendFile('/js/journals.js?v='.$ver);
$this->headScript()->appendFile('/js/change_order.js?v='.$ver);
$this->headScript()->appendFile('/js/material_location.js?v='.$ver);
$this->headScript()->appendFile('/js/tags.js?v='.$ver);
$this->headScript()->appendFile('/js/favorites.js?v='.$ver);
$this->headScript()->appendFile('/js/jquery-ui-timepicker-addon.js'); 
$this->headScript()->appendFile('/plupload/js/plupload.full.js');    
$this->headScript()->appendFile('/js/highcharts_4.04.js');
$this->headScript()->appendFile('/js/jquery.autogrow.js?v='.$ver);
?>

<script type="text/javascript">

    $(function(){ 

        project.initReloadableProjectTabs($("#project_id").val());
        pronav.setUpProgressBars();
        pronav.project.submittals.makeSubmittalsTableSortable();
        pronav.project.rfis.makeRFITableSortable();
        pronav.project.journals.makeTableSortable();

        $("#tabs-min").tabs({
            select: function(event, ui){
                $("#lastTab").val(ui.panel.id);
            }
        }).show();       

        $("#progress_subtabs_container").tabs().show();

        //tab direction might be in url as parameter 'tab'.
        url_tab = pronav.getURLParameter('tab');
        if (url_tab){
            $("#lastTab").val(url_tab);
        }

        $('a[href=#'+$("#lastTab").val()+']').trigger('click')

        $("#project-select-details, #project-select-notes, #project-select-files, #project-select-progress").on("change",function(e){
            var tab = $("#lastTab").val();
            if(tab == "") tab = "overview";
            window.location = pronav.printf("/project/view/id/%s?tab=%s",$(this).val(), tab);
        });                    

        if (pronav.getURLParameter('auth') == 1){
            //user directed to authorize project. Open the dialog. 
            $("#auth_quick_link").click();
        }                                                        
    });
</script>


<img id="loading_long" src="/images/ajax-loader-long.gif" alt="loading..." style="display: none;"/>
<h1>Project Information</h1>  
<!-- Moved hidden content to bottom of page. IE7 was jumping when dialogs were loading. --> 

<input type="hidden" id="lastTab" value="<?= $this->selected_tab ?>" />
<div style="height: 16px; float: left;">
    <div class="bread-crumb" style="float: left; margin-right: 2px;"><a href="/project/index">List All Projects</a></div>
</div>

<div style="float: right;margin-right:8px;margin-bottom:2px;" class="section-header-menuList ">

    <? if(ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_OVERVIEW_EDIT)): ?>
        <?= $this->projectinfo->getTrimNextStage($this->projectinfo->project_id) ?>
        <? else: ?>
        <?= $this->projectinfo->getClientNextStage($this->projectinfo->project_id) ?>
        <? endif; ?>  
</div>
<input type="hidden" id="cur-stage" value="<?= $this->projectinfo->stage_id ?>"/>
<input type="hidden" id="base_project_id" value="<?= $this->projectinfo->project_id ?>"/>

<div class="overview"> 
    <table border="0" cellpadding="0" cellspacing="0" style="width:100%;">
        <tr id="first-row">
            <td colspan="2">
                <? if($this->projectinfo->stage_id == ProNav_Utils::STAGE_CANCELLED || $this->projectinfo->stage_id == ProNav_Utils::STAGE_POTENTIAL): ?>
                    <div style="color:red;font-size:10pt;">Internal</div>
                    <? endif; ?>
                <?= $this->projectinfo->DoneAtLocation ? $this->projectinfo->DoneAtLocation->getCombinedName(false) : "" ?>

            </td>
            <td>
                <?
                $favorite = $this->projectinfo->favorite;
                $favorite_url = $favorite ? '/images/project_favorite_on.png' : '/images/project_favorite_off.png';
                $favorite_url_alt = !$favorite ? '/images/project_favorite_on.png' : '/images/project_favorite_off.png';
                ?>
                <img id="favorite_star_img" src="<?= $favorite_url; ?>" 
                    data-altsrc="<?= $favorite_url_alt; ?>"
                    class="project_favorite <?= $this->projectinfo->favorite ? 'on' : 'off'; ?>" 
                    style="<?= $this->userIsOnTeam ? '' : 'visibility:hidden;'; ?>"
                    title="Add/Remove Star" id="project_favorite" 
                    onclick="pronav.favorites.setFavorite(this, <?= $this->projectinfo->project_id; ?>)" />                                
            </td>
        </tr>
        <tr id="second-row">
            <td><?= $this->projectinfo->title ?></td>
            <td id="base-project-job-no" nowrap="nowrap" style="width: 160px;text-align:center;">
                <? if($this->projectinfo->job_no): ?>
                    Job No.: <?= $this->projectinfo->job_no; ?>
                    <? else: ?>
                    &nbsp;
                    <? endif; ?>
            </td>
            <td nowrap="nowrap" style="width: 350px;text-align:right;" >
                Project No.: <?= $this->projectinfo->getIdDisplay(); ?>
                <span class="bullet">&bull;</span>
                <?= $this->projectinfo->stage_title;?>
            </td>
        </tr>
    </table>
</div>

<?
//Tab and section logic consolidated here (b/c it exists in 2 places below). 
$isBase =  $this->isBase;
$notEmployee = !ProNav_Auth::isEmployee();
$showProgress = (($notEmployee && $this->projectinfo->showProgress() && $this->projectinfo->access_pct_completed)|| (ProNav_Auth::isEmployee() && ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_PROGRESS_VIEW_TAB)));
$showAccounting = ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_ACCOUNTING_VIEW);
$showAcquisition =  ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SALES_VIEW);
$showCustomerNotes = (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_CUSTOMER_NOTES) &&
    (count($this->customerNotes[Application_Model_Note::CORPORATION]) > 0 ||
        count($this->customerNotes[Application_Model_Note::WORKGROUP]) > 0 ||
        count($this->customerNotes[Application_Model_Note::LOCATION]) > 0));
$showHistory =  ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_HISTORY_VIEW);
$showSubmittals = ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SUBMITTAL_VIEW);
$showRFIs =  ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_RFI_VIEW);
$showJournals = ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_JOURNAL_VIEW) && ($this->projectinfo->stage_id == ProNav_Utils::STAGE_OPEN || $this->projectinfo->stage_id == ProNav_Utils::STAGE_CLOSED);
$showProjectValue = $notEmployee|| ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_VALUE_VIEW);
$showScope = $notEmployee || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SCOPE_VIEW);
$showChangeOrders = $notEmployee || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_CHANGE_ORDER_VIEW);
$showNotes = $notEmployee || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_NOTES_VIEW);
$showFiles = $notEmployee || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_FILES_VIEW_TAB);
$showTeam = $notEmployee || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_TEAM_VIEW);
?>

<div id="tabs-min" class="tabs-min" style="display: none;">

    <ul style="width:100%" id="project_tabs">
        <li><a href="#overview">Overview</a></li>
        <? if($showChangeOrders):?>
            <li><a href="#change_orders">Change Orders</a></li>
            <? endif; ?>
        <? if($showNotes): ?>
            <li><a href="#notes">Notes</a></li>
            <? endif; ?>
        <? if($showFiles): ?>
            <li><a href="#files">Files</a></li>
            <? endif; ?>
        <? if ($showProgress) : ?>
            <li><a href="#progress">Progress</a></li>
            <? endif; ?>
        <? if($showRFIs): ?>    
            <li><a href="#rfis">RFIs</a></li>  
            <? endif; ?>
        <? if($showSubmittals): ?>
            <li><a href="#submittals">Submittals</a></li>
            <? endif; ?>
        <? if($showJournals): ?>
            <li><a href="#journals">Job Journals</a></li>
            <? endif; ?>
        <? if($showTeam): ?>
            <li><a href="#project-team">Team</a></li>
            <? endif; ?>
    </ul>

    <div id="overview">

        <?= $this->general_info; ?>

        <? if($showCustomerNotes) : ?>
            <!-- Customer Notes -->
            <div id="customer-notes-main">
                <div class="section-header">
                    <span class="section-header-title">Customer Notes</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt" class="internal">Internal</span>
                    <div class="section-header-menuList">
                        <a id="projectNotesToggle" class="note-toggle-all" style="margin-right:10px;" 
                            href="javascript:void(0);">Show All</a>
                    </div>
                </div>
                <div id="noteSectionData" class="section">
                    <?= $this->customerNotesTable; ?>
                </div>
            </div>
            <? endif; ?>

        <? if($showProjectValue): ?>
            <?= $this->project_value; ?>
            <? endif; ?>

        <!-- Scope of Work -->
        <? if($showScope): ?>
            <div>
                <div class="section-header">
                    <span class="section-header-title">Project Scope of Work</span>
                    <? if (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SCOPE_EDIT)) : ?>
                        <div class="section-header-menuList">
                            <a href="javascript:void(0);" onclick="project.loadEditScope(<?= $this->projectinfo->project_id ?>);">Edit</a>
                        </div>
                        <div id="scope-edit"></div>
                        <? endif;?>
                </div>
                <div id="scope" class="section">
                    <?= $this->scope; ?>
                </div>
            </div>
            <? endif; ?>
			
		 <!-- Material Location -->
        
            <div>
                <div class="section-header">
                    <span class="section-header-title">Project Material Location</span>
                    <? if (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SCOPE_EDIT)) : ?>
                        <div class="section-header-menuList">
                            <a href="javascript:void(0);" id="loadEditMaterialLocation" onclick="project.loadEditMaterialLocation(<?= $this->projectinfo->project_id ?>);">Edit</a>
							
							 <a href="javascript:void(0);" id="saveMaterialLocation" style="display:none;" onclick="project.saveMaterialLocation(<?= $this->projectinfo->project_id ?>);">Save</a>&nbsp;
							 
							  <a href="javascript:void(0);" id="cancelMaterialLocation" style="display:none;" onclick="project.cancelMaterialLocation(<?= $this->projectinfo->project_id ?>);">Cancel</a>
							
							
	
                        </div>
                        <div id="material-location-edit"></div>
                        <? endif;?>
                </div>
                <div id="material-location" class="section">
                    <?= $this->material; ?>
                </div>
				
				
				<div id="editMaterialForm">
						
				
				
				</div>
            </div>
            

        <? if($showAccounting) : ?>
            <div id="accounting-details">  
                <div class="section-header">
                    <span class="section-header-title">Project Accounting</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt; float:left;" class="internal">Internal</span>
                    <div class="section-header-menuList">
                        <? if (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_ACCOUNTING_EDIT)): ?>
                            <a href="javascript:void(0);" onclick="pronav.project.accounting.loadEditDialog(<?= $this->projectinfo->project_id ?>);">Edit</a>
                            <div id="accoutingEdit" style="display:none"></div>
                            <? endif; ?>
                    </div>        
                </div>   
                <div id="accounting-section" class="section">
                    <?= $this->accounting; ?>
                </div>
            </div>
            <? endif; ?>

        <? if ($showAcquisition): ?>
            <div id="acquisition">    
                <div class="section-header">
                    <span class="section-header-title">Project Sales</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt; float:left;" class="internal">Internal</span>
                    <? if (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SALES_EDIT)): ?>
                        <div class="section-header-menuList">
                            <a href="javascript:void(0);" onclick="pronav.project.acquisition.loadEditDialog(<?= $this->projectinfo->project_id ?>);">Edit</a>
                            <div id="edit_acquisition" style="display:none"></div>        
                        </div>
                        <? endif; ?>
                </div>
                <div class="section">
                    <?= $this->work_acquisition; ?>
                </div>
            </div>
            <? endif; ?> 

        <? if ($this->tagSelections && ProNav_Auth::hasPerm(ProNav_Auth::PERM_SYSTEM_TAGS_GENERAL)){
            echo $this->partial('tags/view.phtml', array('tagSelections' => $this->tagSelections));
        }?>    

        <!-- Change History -->
        <? if ($showHistory): ?>
            <div id="change-history-main">
                <div class="section-header">
                    <span class="section-header-title">Project History</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt" class="internal">Internal</span>
                    <div class="section-header-menuList">
                    </div>
                </div>
                <div class="section"><?= $this->stagehistory ?></div>
            </div>
            <? endif;?>
    </div>

    <? if ($showProgress) : 
        $show_labor_prod = ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_LABOR_PROD_VIEW) && $this->project_labor;
        $show_ppa = ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_PPA_VIEW) && $this->project_analysis;  
        $show_progress_tabs = ($show_labor_prod || $show_ppa) && ProNav_Auth::isEmployee();
        ?>                                                                                         
        <div id="progress" class="<?= $show_progress_tabs ? '' : 'no_tabs'; ?>">
            <? if ($show_progress_tabs): ?>
                <div id="progress_subtabs_container" class="tabs-min" style="display: none;"> 
                    <ul>
                        <li><a href="#project_task_tab_container">Project Tasks</a></li>
                        <li><a href="#project_punch_list_tab_container">Punch List</a></li>
                        <? if ($show_labor_prod): ?>
                            <li><a href="#project_labor_tab_container">Labor Productivity</a></li>
                            <? endif; ?>
                        <? if ($show_ppa): ?>
                            <li><a href="#analysis_module_tab_container">Post-Project Analysis</a></li>
                            <? endif; ?>
                    </ul>

                    <div id="project_task_tab_container"> <!-- to compensate for ajax reloading and tab classes added to the div. -->
                        <?= $this->project_tasks; ?>
                    </div>
                    
                    <div id="project_punch_list_tab_container"> <!-- to compensate for ajax reloading and tab classes added to the div. -->
                        <?= $this->project_punch_list; ?>
                    </div>

                    <? if ($show_labor_prod): ?>
                        <!-- Project Labor Module -->
                        <div id="project_labor_tab_container">
                            <?= $this->project_labor; ?>
                        </div>
                        <? endif; ?>

                    <? if ($show_ppa): ?>
                        <!-- Project Analysis Module -->
                        <div id="analysis_module_tab_container">
                            <?= $this->project_analysis; ?> 
                        </div>
                        <? endif; ?>                    
                </div>
                <? else: 
                echo $this->project_tasks;
                endif; ?>
        </div>      
        <? endif; ?>

    <!-- Change Orders -->
    <? if($showChangeOrders): ?>
        <div id="change_orders">
            <?= $this->cors; ?>
        </div>
        <? endif; ?>

    <!-- Tab: Notes -->
    <? if($showNotes): ?>
        <div id="notes">
            <!-- Project Notes -->
            <div id="project-notes-main">
                <?= $this->project_notes ?>
            </div>
        </div>
        <? endif; ?>

    <!-- Tab: Files -->
    <? if($showFiles): ?>
        <div id="files">
            <!-- File Folders -->
            <a name="filefolders"></a>
            <div id="filefolders">
                <?= $this->files; ?>
            </div>
        </div>
        <? endif; ?>

    <? if($showSubmittals): ?>
        <!-- Tab: Submittals -->
        <div id="submittals">
            <div class="section-header">
                <span class="section-header-title">Submittals</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt" class="internal">Internal</span>
                <div class="section-header-menuList">
                    <? if (ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_SUBMITTAL_ADD_EDIT)): ?>
                        <a onclick="pronav.project.submittals.loadEditDialog(0, <?= $this->projectinfo->project_id; ?> );" href="javascript:void(0);">Add Submittal</a>
                        <? endif; ?>
                    <div style="display:none" id="submittalEdit"></div>
                    <div style="display:none" id="submittalView"></div>
                </div>
            </div>
            <div id="submittals-section" class="section"><?= $this->submittals ?></div>
        </div>        
        <? endif; ?>

    <!-- RFIs -->
    <? if ($showRFIs): ?>
        <div id="rfis">
            <div class="section-header">
                <span class="section-header-title">RFIs</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt" class="internal">Internal</span>
                <div class="section-header-menuList">
                    <? if(ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_RFI_ADD_EDIT)): ?>
                        <a onclick="pronav.project.rfis.addEditDialog(0, <?= $this->projectinfo->project_id; ?>);" href="javascript:void(0);">Add RFI</a>
                        <? endif; ?>
                    <div style="display:none" id="rfiEdit"></div>
                    <div style="display:none" id="rfiView"></div>
                </div>
            </div>
            <div id="rfis-section" class="section"><?= $this->rfis ?></div>
        </div> 
        <? endif;?> 

    <? if ($showJournals): ?>
        <!-- Job Journals -->
        <div id="journals">
            <div class="section-header">
                <span class="section-header-title">Job Journals</span> <span style="margin-left:10px; font-weight:normal; font-size:10pt" class="internal">Internal</span>
                <div class="section-header-menuList">
                    <? if($this->has_incomplete_journal): ?>
                        <span title="Last Job Journal was not submitted" style="color:#999;">Add Job Journal</span>
                        <? else: ?>
                        <a onclick="pronav.project.journals.addEditDialog(0, <?= $this->projectinfo->project_id ?>);" href="javascript:void(0);">Add Job Journal</a>
                        <? endif; ?>
                    <div style="display:none" id="journalDg"></div>
                    <div style="display:none" id="journalHelperDg"></div>
                </div>
            </div>
            <div id="journals-section" class="section"><?= $this->journals ?></div>
        </div>
        <? endif; ?>    

    <!-- Project Team -->
    <? if($showTeam): ?>
        <div id="project-team">
            <div class="section-header">
                <span class="section-header-title">Project Team</span>
                <div class="section-header-menuList">
                    <? 
                    $showedAssignUsers = false;
                    if (!ProNav_Auth::isEmployee() || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_TEAM_ADD_CUSTOMERS, ProNav_Auth::PERM_PROJECTS_TEAM_ADD_OTHERS, ProNav_Auth::PERM_PROJECTS_TEAM_ADD_TRIM, ProNav_Auth::PERM_PROJECTS_TEAM_REMOVE_USERS)):?>
                        <a href="javascript:void(0);" onclick="pronav.project.team.assignUsers(<?= $this->projectinfo->project_id ?>);">Assign Users</a>                        
                        <? 
                        $showedAssignUsers = true;
                        endif; 
                    ?>
                    <? if (!ProNav_Auth::isEmployee() || ProNav_Auth::hasPerm(ProNav_Auth::PERM_PROJECTS_TEAM_ADD_REMOVE_ME)): 
                        if ($showedAssignUsers): ?>
                            <span class="bullet">&bull;&nbsp;</span>
                            <? endif; ?>
                        <a id="userProjectTeamToggle" href="javascript:void(0);" onclick="pronav.project.team.toggleMe(<?= $this->projectinfo->project_id ?>);"><?= $this->userIsOnTeam ? "Remove Me From The Team" : "Add Me To The Team";?></a>
                        <? endif; ?>

                    <div id="edit_project_team" style="display: none;"></div>
                </div>
            </div>
            <div id="project_team_section" class="section">
                <?= $this->project_team; ?>
            </div>
        </div>
        <? endif; ?>

</div>

<div id="err-div"></div>
<div id="project-info-edit"></div> 
<div id="uploader-dg"></div>
<div id="other-projects"></div>
<div id="loading-div" style="display:none;height:30px;"></div>
<input type="hidden" id="project_id" value="<?= $this->projectinfo->project_id ?>"/>